# Generated by Django 5.2.18 on 2026-10-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('quiz', '0002_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teacher_profiles', to='quiz.subject', verbose_name='пәндер'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='quiz.subject', verbose_name='пән'),
        ),
    ]
