# Generated by Django 5.2.18 on 2026-10-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subject'),
        ('quiz', '0004_subject_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='quiz.subject', verbose_name='пән'),
        ),
    ]
