# Generated by Django 5.2.18 on 2026-10-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subject_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='language',
            field=models.CharField(choices=[('kk', 'Қазақша'), ('ru', 'Орысша')], help_text='Топ студенттерінің тесттері осы тілде өтеді.', max_length=2, null=True, verbose_name='оқыту тілі'),
        ),
    ]
