# Generated by Django 5.2.18 on 2026-10-07 05:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='мәтіні')),
                ('is_correct', models.BooleanField(default=False, verbose_name='дұрыс')),
            ],
            options={
                'verbose_name': 'жауап нұсқасы',
                'verbose_name_plural': 'жауап нұсқалары',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('kk', 'Қазақша'), ('ru', 'Орысша')], max_length=2, verbose_name='тілі')),
                ('title', models.CharField(max_length=255, verbose_name='атауы')),
                ('text', models.TextField(verbose_name='мәтіні')),
                ('code', models.TextField(blank=True, verbose_name='коды')),
                ('image', models.ImageField(blank=True, upload_to='contexts/', verbose_name='суреті')),
                ('is_demo', models.BooleanField(default=False, verbose_name='демо')),
                ('is_active', models.BooleanField(default=True, verbose_name='белсенді')),
            ],
            options={
                'verbose_name': 'контекст',
                'verbose_name_plural': 'контексттер',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='нөмірі')),
                ('name_kk', models.CharField(max_length=255, verbose_name='атауы (қаз)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='атауы (орыс)')),
            ],
            options={
                'verbose_name': 'тақырыпша',
                'verbose_name_plural': 'тақырыпшалар',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='нөмірі')),
                ('name_kk', models.CharField(max_length=255, verbose_name='атауы (қаз)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='атауы (орыс)')),
            ],
            options={
                'verbose_name': 'тақырып',
                'verbose_name_plural': 'тақырыптар',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='атауы')),
                ('opens_at', models.DateTimeField(verbose_name='ашылу уақыты')),
                ('closes_at', models.DateTimeField(verbose_name='жабылу уақыты')),
                ('show_answers', models.CharField(choices=[('after_finish', 'Тест аяқталған бойда'), ('after_close', 'Сессия жабылғаннан кейін')], default='after_finish', max_length=20, verbose_name='дұрыс жауаптарды көрсету')),
                ('is_active', models.BooleanField(default=True, verbose_name='белсенді')),
                ('groups', models.ManyToManyField(blank=True, related_name='exam_sessions', to='accounts.studygroup', verbose_name='топтар')),
            ],
            options={
                'verbose_name': 'тест сессиясы',
                'verbose_name_plural': 'тест сессиялары',
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('kk', 'Қазақша'), ('ru', 'Орысша')], max_length=2, verbose_name='тест тілі')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='басталған уақыты')),
                ('deadline', models.DateTimeField(verbose_name='мерзімі')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='аяқталған уақыты')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='балы')),
                ('status', models.CharField(choices=[('in_progress', 'Жүріп жатыр'), ('finished', 'Аяқталды')], default='in_progress', max_length=20, verbose_name='күйі')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='студент')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='quiz.examsession', verbose_name='сессия')),
            ],
            options={
                'verbose_name': 'тест әрекеті',
                'verbose_name_plural': 'тест әрекеттері',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('kk', 'Қазақша'), ('ru', 'Орысша')], max_length=2, verbose_name='тілі')),
                ('text', models.TextField(verbose_name='сұрақ мәтіні')),
                ('image', models.ImageField(blank=True, upload_to='questions/', verbose_name='суреті')),
                ('code', models.TextField(blank=True, verbose_name='коды')),
                ('level', models.CharField(choices=[('A', 'A — базалық'), ('B', 'B — орташа'), ('C', 'C — жоғары')], max_length=1, verbose_name='деңгейі')),
                ('is_demo', models.BooleanField(default=False, verbose_name='демо')),
                ('is_active', models.BooleanField(default=True, verbose_name='белсенді')),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='quiz.context', verbose_name='контекст')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='quiz.subtopic', verbose_name='тақырыпша')),
            ],
            options={
                'verbose_name': 'сұрақ',
                'verbose_name_plural': 'сұрақтар',
                'ordering': ['subtopic__number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='реті')),
                ('answer_order', models.JSONField(default=list, verbose_name='нұсқалар реті')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quiz.attempt', verbose_name='тест әрекеті')),
                ('selected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.answer', verbose_name='таңдалған жауап')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_items', to='quiz.question', verbose_name='сұрақ')),
            ],
            options={
                'verbose_name': 'нұсқадағы сұрақ',
                'verbose_name_plural': 'нұсқадағы сұрақтар',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question', verbose_name='сұрақ'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtopics', to='quiz.topic', verbose_name='тақырып'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('user', 'session'), name='unique_attempt_per_session'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'order'), name='unique_order_in_attempt'),
        ),
    ]
