# Generated by Django 5.2.18 on 2026-10-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='коды')),
                ('name_kk', models.CharField(max_length=255, verbose_name='атауы (қаз)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='атауы (орыс)')),
                ('duration_minutes', models.PositiveSmallIntegerField(verbose_name='тест уақыты (минут)')),
                ('uses_formulas', models.BooleanField(default=False, verbose_name='формулалар қолданылады')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='реті')),
                ('is_active', models.BooleanField(default=True, verbose_name='белсенді')),
            ],
            options={
                'verbose_name': 'пән',
                'verbose_name_plural': 'пәндер',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['topic__subject__order', 'number'], 'verbose_name': 'тақырыпша', 'verbose_name_plural': 'тақырыпшалар'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['subject__order', 'number'], 'verbose_name': 'тақырып', 'verbose_name_plural': 'тақырыптар'},
        ),
        migrations.AddField(
            model_name='subtopic',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='сипаттамасы (қаз)'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='нөмірі'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='нөмірі'),
        ),
        migrations.AddField(
            model_name='context',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contexts', to='quiz.subject', verbose_name='пән'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='quiz.subject', verbose_name='пән'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='quiz.subject', verbose_name='пән'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('subject', 'number'), name='unique_topic_number_in_subject'),
        ),
    ]
