# Generated by Django 5.2.18 on 2026-10-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_informatics_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contexts', to='quiz.subject', verbose_name='пән'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='quiz.subject', verbose_name='пән'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='quiz.subject', verbose_name='пән'),
        ),
    ]
