# Generated by Django 5.2.18 on 2026-10-07 13:27

import apps.quiz.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_subject_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.quiz.models.answer_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.quiz.models.validate_image_size], verbose_name='суреті'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, verbose_name='мәтіні'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='questions/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.quiz.models.validate_image_size], verbose_name='суреті'),
        ),
    ]
